### ISSUE TITLE
YAML listed as prerequisite, but not used anywhere

### ISSUE THREAD

**Issue by perlpunk** [VVelox/CAPE-Utils#2]
Hi,

I was just looking around reverse dependencies of YAML modules and found this, which lists YAML.pm as a requirement, but doesn't use it.
So maybe you want to drop it.
If you later want to use YAML, it might be a good idea to use YAML::PP instead.
(edit: and maybe you also want to switch the module in https://metacpan.org/dist/YAML-yq-Helper )

**Comment by VVelox** [comment]
@perlpunk Awesome, thanks!

Removed it. I want to say I was thinking of replacing Config::Tiny with it at one time but never got around to it.

Noted in changelog will be present in next release. :)
